name: UnitTests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual run'

jobs:
  pgetinker-tests:

    runs-on: self-hosted

    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build PGEtinker Docker Images
        run: |
          cp .env.sail .env
          ./scripts/pgetinker build

      - name: Initialize PGEtinker
        run: ./scripts/pgetinker initialize ci
      
      - name: Start PGEtinker
        run: ./scripts/pgetinker up -d

      - name: Run Unit Tests
        run: ./scripts/pgetinker test

      - name: Start PGEtinker
        run: ./scripts/pgetinker down

      # - name: Get Commit Hash
      #   id: vars
      #   run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      # - name: Add "VERSION" hashes to .env
      #   run: echo -e "VERSION=${{ steps.vars.outputs.sha }}\nVITE_VERSION=${{ steps.vars.outputs.sha }}" >> .env.example
